@startuml
!theme plain
skinparam backgroundColor white
skinparam shadowing false
skinparam packageStyle rectangle
skinparam ArrowColor #444441
skinparam ArrowFontSize 11

left to right direction

actor "Пользователь" as User

package "Уровень представления" <<Layer>> {
    package "Управление клиентами" as CustomerAPI
    package "Управление заказами" as OrderAPI
    package "Управление ресторанами" as RestaurantAPI
    package "Управление курьерами" as CourierAPI
    package "Управление отзывами" as ReviewAPI
}

package "Уровень бизнес-логики" <<Layer>> {
    package "Обработка заказов" {
        package "Расчёт стоимости" as OrderService
        package "Обработка платежей" as PaymentService
        package "Управление статусами" as StatusService
    }
    package "Управление доставкой" {
        package "Назначение курьеров" as CourierService
    }
    package "Качество сервиса" {
        package "Обработка отзывов" as ReviewService
        package "Расчёт рейтингов" as RatingService
    }
    package "Вспомогательные" {
        package "Валидация данных" as ValidationService
    }
}

package "Уровень доступа к данным" <<Layer>> {
    package "Репозитории" as Repositories
}

database "База данных" as DB

User ..> CustomerAPI   : use
User ..> OrderAPI      : use
User ..> RestaurantAPI : use
User ..> CourierAPI    : use
User ..> ReviewAPI     : use

CustomerAPI   ..> ValidationService : use
OrderAPI      ..> OrderService      : use
OrderAPI      ..> PaymentService    : use
RestaurantAPI ..> ValidationService : use
CourierAPI    ..> CourierService    : use
CourierAPI    ..> StatusService     : use
ReviewAPI     ..> ReviewService     : use

ReviewService ..> RatingService : call

OrderService      ..> Repositories : use
PaymentService    ..> Repositories : use
CourierService    ..> Repositories : use
ValidationService ..> Repositories : use
StatusService     ..> Repositories : use
ReviewService     ..> Repositories : use
RatingService     ..> Repositories : use

Repositories ..> DB : use
@enduml